<?php

namespace App\Constant;

class TripConstant
{
    const REQUEST_TO_FIND_TRIP_TRUCK = 'REQUEST_TO_FIND_TRIP_TRUCK';
    const ASSIGN_TRIP_TO_TRUCK = 'ASSIGN_TRIP_TO_TRUCK';
    const ACCEPT_TRIP_ASSIGN = 'ACCEPT_TRIP_ASSIGN';
    const TRUCK_TO_STORE = 'TRUCK_TO_STORE';
    const TRUCK_GET_CONSIGNMENTS = 'TRUCK_GET_CONSIGNMENTS';
    const TRUCK_TO_DESTINATION = 'TRUCK_TO_DESTINATION';
    const TRUCK_DELIVERED_CONSIGNMENTS = 'TRUCK_DELIVERED_CONSIGNMENTS';
}